export const URL_API = 'https://api.unsplash.com';
export const URL_AUTH = 'https://unsplash.com/oauth/authorize?';
export const URL_TOKEN = 'https://unsplash.com/oauth/token?';
export const ACCESS_KEY = 'mzUpcXjeMJFWQJJIcxz98TsB5FDj1W1EdhiTYJRJLG0';
export const SECRET_KEY = 'FucXnUSi4Gnea3cSjRfxVgzzKPnbaTXwDsfANS4AEes';
export const RESPONSE_TYPE = 'code';
export const GRANT_TYPE = 'authorization_code';
export const REDIRECT_URI = 'http://localhost:3000/auth';
export const SCOPE = 'public read_user read_photos write_likes';
